"""Paddock's site map projected as a validated nginx configuration tree.

One Caddyfile became a tree of files, which introduces an atomicity problem a
single file did not have: a partially written tree followed by any reload — a
crash between writes, or an external `systemctl reload` — would load a
half-generated configuration. Every projection is therefore written into its
own numbered generation directory and promoted by renaming one symlink, which
is atomic. The previous generations stay on disk for rollback and diagnosis.

`nginx.conf` lives inside its generation and includes its site blocks with a
relative path, so the same rendered bytes validate in a staging directory and
run under `current/`. Only that include is relative; the pid file, logs, and
temporary paths are absolute, because they are shared across generations and
must not move when one is promoted.

The projector keeps the four-method shape its callers already use — render,
validate, write, reload — and the candidate stays opaque, so the transaction
ordering that writes state between `validate` and `write` is unchanged. That
ordering is what makes a rejected configuration leave both disk and state
untouched.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil
import subprocess
from typing import Any, Callable, Mapping

from . import drivers, siteconfig
from .paths import Paths


class WebError(RuntimeError):
    pass


Runner = Callable[..., subprocess.CompletedProcess[str]]

UNIT = "paddock-web.service"

# Shipped by the nginx package, which Paddock depends on. `mime.types` maps
# extensions for the static file server; `fastcgi_params` is the standard CGI
# variable set that every PHP block builds on.
MIME_TYPES = "/etc/nginx/mime.types"
FASTCGI_PARAMS = "/etc/nginx/fastcgi_params"

# Kept for rollback and for diffing what changed. Older generations are pruned
# on promotion, so a long-lived installation does not accumulate them.
GENERATIONS_KEPT = 3

ADDRESS = "127.0.0.1"


@dataclass(frozen=True)
class Generation:
    """One complete, self-consistent nginx tree awaiting validation.

    Callers treat this as opaque. `directory` is allocated by `render` so that
    `validate` can materialize exactly the bytes `write` will promote, rather
    than staging the tree twice and hoping the second render matches.
    """

    directory: Path
    files: Mapping[str, str]


class WebProjector:
    def __init__(self, paths: Paths, runner: Runner = subprocess.run):
        self.paths = paths
        self.runner = runner

    @property
    def root(self) -> Path:
        return self.paths.state / "nginx"

    @property
    def current(self) -> Path:
        return self.root / "current"

    @property
    def path(self) -> Path:
        """The configuration path the running unit reads."""
        return self.current / "nginx.conf"

    @property
    def generations(self) -> Path:
        return self.root / "generations"

    # ------------------------------------------------------------------ render

    def render(self, sites: dict[str, dict[str, Any]]) -> Generation:
        files = {
            "nginx.conf": self._main(),
            "snippets/php-fastcgi.conf": self._php_snippet(),
            "snippets/proxy.conf": self._proxy_snippet(),
            "sites/000-default.conf": self._catch_all(),
        }
        for name, site in sorted(sites.items()):
            files[f"sites/{name}.conf"] = self._site(name, site)
        return Generation(self._next_generation(), files)

    def _main(self) -> str:
        temporary = self.root / "tmp"
        return "\n".join(
            [
                "# Generated by Paddock. Every edit is lost on the next projection.",
                "daemon off;",
                "worker_processes 2;",
                f"pid {_quote(self.root / 'nginx.pid')};",
                f"error_log {_quote(self.paths.state / 'logs' / 'nginx.log')} warn;",
                # Only ever created if nginx falls back to the accept mutex,
                # but its built-in default is under /run, which
                # ProtectSystem=strict mounts read-only along with everything
                # else outside /dev, /proc and /sys.
                f"lock_file {_quote(self.root / 'nginx.lock')};",
                "",
                "events {",
                "\tworker_connections 1024;",
                "}",
                "",
                "http {",
                f"\tinclude {MIME_TYPES};",
                "\tdefault_type application/octet-stream;",
                "",
                # Every site declares its own JSON access log, but the
                # http-level default is still opened, and its built-in path is
                # /var/log/nginx/access.log — which the desktop user cannot
                # write. Turning it off here leaves each server's own log as
                # the only one, which is the design.
                "\taccess_log off;",
                "",
                "\tsendfile on;",
                "\ttcp_nopush on;",
                "\ttypes_hash_max_size 4096;",
                "\tserver_tokens off;",
                "\tssl_session_cache shared:paddock:8m;",
                "\tssl_session_timeout 1h;",
                "\tabsolute_redirect off;",
                "\tserver_name_in_redirect off;",
                "\tclient_max_body_size 256m;",
                "",
                # All five, not only the ones Paddock uses. nginx creates a
                # temporary directory for every proxying module compiled in,
                # at startup and during `nginx -t`, whether or not the module
                # is configured. Leaving uwsgi and scgi at their built-in
                # /var/lib/nginx defaults made setup fail with EACCES: the
                # unit runs as the desktop user under ProtectSystem=strict.
                f"\tclient_body_temp_path {_quote(temporary / 'client-body')};",
                f"\tproxy_temp_path {_quote(temporary / 'proxy')};",
                f"\tfastcgi_temp_path {_quote(temporary / 'fastcgi')};",
                f"\tuwsgi_temp_path {_quote(temporary / 'uwsgi')};",
                f"\tscgi_temp_path {_quote(temporary / 'scgi')};",
                "",
                "\t# PHP applications read HTTPS to decide the scheme they",
                "\t# generate URLs with. nginx never sets it, so without this a",
                "\t# secured site emits http:// links to itself.",
                "\tmap $scheme $paddock_https {",
                "\t\thttps on;",
                "\t\tdefault '';",
                "\t}",
                "",
                "\t# Websocket upgrades for site Reverb workers. Connection must",
                "\t# be close on a plain request, or keepalive breaks.",
                "\tmap $http_upgrade $paddock_connection {",
                "\t\tdefault upgrade;",
                "\t\t'' close;",
                "\t}",
                "",
                "\tlog_format paddock escape=json '{'",
                "\t\t'\"time\":\"$time_iso8601\",'",
                "\t\t'\"remote_addr\":\"$remote_addr\",'",
                "\t\t'\"method\":\"$request_method\",'",
                "\t\t'\"host\":\"$host\",'",
                "\t\t'\"uri\":\"$request_uri\",'",
                "\t\t'\"status\":$status,'",
                "\t\t'\"bytes\":$body_bytes_sent,'",
                "\t\t'\"duration\":$request_time,'",
                "\t\t'\"referer\":\"$http_referer\",'",
                "\t\t'\"user_agent\":\"$http_user_agent\"'",
                "\t'}';",
                "",
                "\t# Relative, so these bytes validate in a staging directory and",
                "\t# run under current/. A glob include tolerates zero sites; a",
                "\t# literal include of a missing file would not.",
                "\tinclude sites/*.conf;",
                "}",
                "",
            ]
        )

    def _php_snippet(self) -> str:
        return "\n".join(
            [
                "# Included by every PHP location.",
                f"include {FASTCGI_PARAMS};",
                "fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;",
                "fastcgi_param DOCUMENT_ROOT $realpath_root;",
                "fastcgi_param SCRIPT_NAME $fastcgi_script_name;",
                "fastcgi_param PATH_INFO $fastcgi_path_info;",
                "fastcgi_param HTTPS $paddock_https if_not_empty;",
                "fastcgi_hide_header X-Powered-By;",
                "fastcgi_buffers 16 16k;",
                "fastcgi_buffer_size 32k;",
                "fastcgi_read_timeout 300s;",
                "",
            ]
        )

    def _proxy_snippet(self) -> str:
        return "\n".join(
            [
                "# Included by proxied locations. proxy_pass stays with the",
                "# location, because only the port differs per site.",
                "proxy_http_version 1.1;",
                "proxy_set_header Upgrade $http_upgrade;",
                "proxy_set_header Connection $paddock_connection;",
                "proxy_set_header Host $host;",
                "proxy_set_header X-Real-IP $remote_addr;",
                "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
                "proxy_set_header X-Forwarded-Proto $scheme;",
                "proxy_read_timeout 3600s;",
                "proxy_send_timeout 3600s;",
                "",
            ]
        )

    def _catch_all(self) -> str:
        """Answer hosts no site claims.

        nginx has no implicit behavior here: without a default server the first
        server block in the tree silently answers for every unknown `.test`
        name, which would serve one project's files under another's hostname.
        The TLS half refuses the handshake rather than presenting some other
        site's certificate, which is the honest answer for a host Paddock does
        not serve and needs no certificate of its own.
        """
        return "\n".join(
            [
                "# Generated by Paddock.",
                "server {",
                f"\tlisten {ADDRESS}:80 default_server;",
                "\tserver_name _;",
                "\tdefault_type text/plain;",
                "\taccess_log off;",
                "\treturn 404 'No Paddock site is linked for this host. Run paddock link in the project directory.';",
                "}",
                "",
                "server {",
                f"\tlisten {ADDRESS}:443 ssl default_server;",
                # `reuseport` may appear only once for an address and port in
                # the whole configuration, so it is anchored here: the
                # catch-all is the one server block that always exists and
                # never moves as sites are linked, secured, or removed. It is
                # also why `check-ports` still has to check UDP 443 — with
                # SO_REUSEPORT a second server shares the socket silently
                # instead of failing to bind, which is the hazard ADR 0003
                # made the preflight mandatory for.
                f"\tlisten {ADDRESS}:443 quic reuseport default_server;",
                "\tssl_reject_handshake on;",
                "}",
                "",
            ]
        )

    def _site(self, name: str, site: dict[str, Any]) -> str:
        hostname = f"{name}.test"
        root = Path(site["root"])
        # Absent for records written before drivers existed, which all
        # described Laravel served from `public`.
        driver = drivers.resolve(site.get("type", drivers.DEFAULT))
        document_root = drivers.document_path(
            root, site.get("document_root", "public")
        )
        socket = self.paths.runtime / "php" / site["php"] / "fpm.sock"
        access_log = self.paths.state / "logs" / "sites" / f"{name}.json"
        lines = ["# Generated by Paddock."]

        if site["secured"]:
            certificate = self.paths.data / "pki" / "sites" / name / "certificate.pem"
            private_key = self.paths.data / "pki" / "sites" / name / "private-key.pem"
            # A secured site answers on 80 as well, so an http:// bookmark or a
            # typed hostname redirects instead of failing to connect. Caddy
            # served no plaintext listener for a secured host at all.
            lines.extend(
                [
                    "server {",
                    f"\tlisten {ADDRESS}:80;",
                    f"\tserver_name {hostname};",
                    "\treturn 301 https://$host$request_uri;",
                    "}",
                    "",
                    "server {",
                    f"\tlisten {ADDRESS}:443 ssl;",
                    # QUIC requires TLS, so only a secured site gets one.
                    f"\tlisten {ADDRESS}:443 quic;",
                    f"\tserver_name {hostname};",
                    f"\tssl_certificate {_quote(certificate)};",
                    f"\tssl_certificate_key {_quote(private_key)};",
                    # TLSv1.3 is what QUIC negotiates over.
                    "\tssl_protocols TLSv1.2 TLSv1.3;",
                    # Both are only negotiated over a TLS listener, so they
                    # belong here rather than in http, where http2 would also
                    # offer h2c on the plaintext port.
                    "\thttp2 on;",
                    "\thttp3 on;",
                    # Nothing reaches HTTP/3 without being told the port
                    # speaks it; `always` so an error response advertises it
                    # too.
                    f"\tadd_header Alt-Svc 'h3=\":443\"; ma=86400' always;",
                ]
            )
        else:
            lines.extend(
                [
                    "server {",
                    f"\tlisten {ADDRESS}:80;",
                    f"\tserver_name {hostname};",
                ]
            )

        lines.extend(
            [
                f"\troot {_quote(document_root)};",
                f"\tindex {' '.join(driver.index)};",
                "\tcharset utf-8;",
                f"\taccess_log {_quote(access_log)} paddock;",
                "",
            ]
        )

        reverb = site.get("reverb")
        if reverb:
            # ^~ outranks the regex PHP location, so an upgrade request is
            # never handed to FPM. Caddy expressed the same precedence with a
            # named matcher placed before php_fastcgi.
            for prefix in ("/app/", "/apps/"):
                lines.extend(
                    [
                        f"\tlocation ^~ {prefix} {{",
                        f"\t\tproxy_pass http://{ADDRESS}:{reverb['port']};",
                        "\t\tinclude snippets/proxy.conf;",
                        "\t}",
                        "",
                    ]
                )

        # Driver locations come first: nginx matches regex locations in order
        # of appearance, so anything that must beat the shared PHP block —
        # WordPress denying PHP under wp-content/uploads, for one — has to be
        # emitted above it.
        for location in driver.locations:
            lines.extend([f"\t{location}", ""])

        lines.extend(
            [
                "\tlocation = /favicon.ico { access_log off; log_not_found off; }",
                "\tlocation = /robots.txt  { access_log off; log_not_found off; }",
                "",
                "\tlocation / {",
                f"\t\ttry_files {driver.try_files};",
                "\t}",
                "",
            ]
        )

        if driver.php:
            lines.extend(
                [
                    "\tlocation ~ \\.php$ {",
                    "\t\tfastcgi_split_path_info ^(.+\\.php)(/.+)$;",
                    f"\t\tfastcgi_pass {_quote('unix:' + str(socket))};",
                    "\t\tfastcgi_index index.php;",
                    "\t\tinclude snippets/php-fastcgi.conf;",
                    "\t}",
                    "",
                ]
            )

        lines.extend(
            [
                "\t# nginx would otherwise serve .env, .git and friends as",
                "\t# plain text. well-known is excepted: ACME challenges and",
                "\t# app manifests live there and are meant to be public.",
                "\tlocation ~ /\\.(?!well-known).* {",
                "\t\tdeny all;",
                "\t}",
            ]
        )

        # Included last so a plain directive here overrides the generated one
        # above it, and by path rather than by copying the contents in, so
        # nginx reports a mistake against the file its author edited.
        #
        # An include is emitted only for a fragment that exists and, for a
        # project fragment, is trusted. A glob that picked one up whenever it
        # appeared would mean an unrelated operation's reload failing on an
        # edit nobody had validated yet; this way the render that notices a
        # fragment is the render that validates it.
        custom = siteconfig.describe(self.paths, name, site).includable
        if custom:
            lines.append("")
            for fragment in custom:
                lines.append(f"\tinclude {_quote(fragment)};")
        lines.extend(["}", ""])
        return "\n".join(lines)

    # ---------------------------------------------------------------- validate

    def validate(self, candidate: Generation) -> None:
        """Materialize the candidate, then let nginx judge it.

        `nginx -t` reads more than syntax: it opens the error log and reads
        every certificate named, so an unreadable leaf key fails here rather
        than at reload. That is stronger than `caddy validate` was, and it is
        why the tree has to exist on disk before the check runs.
        """
        self._prepare_directories()
        directory = candidate.directory
        shutil.rmtree(directory, ignore_errors=True)
        try:
            for relative, content in candidate.files.items():
                destination = directory / relative
                destination.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
                destination.write_text(content, encoding="utf-8")
                destination.chmod(0o600)
            self._test(directory / "nginx.conf", directory)
        except Exception:
            shutil.rmtree(directory, ignore_errors=True)
            raise

    def _test(self, configuration: Path, prefix: Path) -> None:
        result = self.runner(
            ["nginx", "-t", "-c", str(configuration), "-p", str(prefix)],
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            detail = result.stderr.strip() or result.stdout.strip() or "unknown error"
            raise WebError(f"nginx rejected generated configuration: {detail}")

    # ------------------------------------------------------------------- write

    def write(self, candidate: Generation) -> None:
        """Promote a validated generation by replacing one symlink.

        `os.replace` on a symlink is a rename, so no reader ever observes a
        missing or half-written `current`.
        """
        if not (candidate.directory / "nginx.conf").is_file():
            raise WebError(
                f"generation was not validated before writing: {candidate.directory}"
            )
        link = self.current.with_name(".current.paddock-new")
        link.unlink(missing_ok=True)
        link.symlink_to(candidate.directory, target_is_directory=True)
        link.replace(self.current)
        self._prune(candidate.directory)

    def _prune(self, keep: Path) -> None:
        try:
            existing = sorted(
                item for item in self.generations.iterdir() if item.is_dir()
            )
        except OSError:
            return
        for directory in existing[:-GENERATIONS_KEPT]:
            if directory != keep:
                shutil.rmtree(directory, ignore_errors=True)

    # ------------------------------------------------------------------ reload

    def reload(self) -> None:
        """Ask systemd to reload, so the unit's own test always gates the signal.

        Signalling the master directly would skip `ExecReload`'s `nginx -t`,
        which is the only gate an external caller — or a future one — passes
        through. The polkit rule already allows the desktop user to manage
        units whose names begin with `paddock-`.
        """
        result = self.runner(
            ["systemctl", "reload", UNIT],
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            detail = result.stderr.strip() or result.stdout.strip() or "unknown error"
            raise WebError(f"nginx reload failed: {detail}")

    def check_live(self) -> None:
        """Validate whatever is currently promoted, for `paddock doctor`."""
        if not self.path.is_file():
            raise WebError(f"not generated: {self.path}")
        self._test(self.path, self.current)

    # ------------------------------------------------------------------ layout

    def _prepare_directories(self) -> None:
        # nginx creates its own temporary paths, but never a log directory: a
        # missing one is a startup failure rather than something it recovers
        # from.
        # `mode` applies only to the leaf a mkdir creates, so the roots are
        # named explicitly and clamped: everything Paddock keeps under state is
        # owner-only, and a parent left at the umask would be the one exception.
        for directory in (
            self.root,
            self.generations,
            self.root / "tmp",
            self.paths.state / "logs",
            self.paths.state / "logs" / "sites",
        ):
            directory.mkdir(parents=True, exist_ok=True, mode=0o700)
            directory.chmod(0o700)

    def _next_generation(self) -> Path:
        highest = 0
        try:
            for item in self.generations.iterdir():
                if item.is_dir() and item.name.isdigit():
                    highest = max(highest, int(item.name))
        except OSError:
            pass
        return self.generations / f"{highest + 1:08d}"


def _quote(path: Path | str) -> str:
    """Quote a path for nginx.

    nginx interpolates `$` inside quoted strings, and offers no escape for it,
    so a project path containing one cannot be expressed. Refusing here names
    the path and the reason; leaving it to `nginx -t` would surface as an
    unknown-variable error pointing at generated configuration the user never
    wrote.
    """
    value = str(path)
    if "$" in value:
        raise WebError(f"nginx cannot address a path containing '$': {value}")
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
